### PR TITLE
Fix message coloring

### LINKED ISSUE #14: Message colour does not change to role colour
I have this option enabled
image
But my messages still aren't coloured
image

### PR DESCRIPTION
**Pull request by Chew**
This implements the same changes from  https://github.com/rauenzi/BetterDiscordApp/commit/f83e053565131084ff249e163e35403bb0a21de2

Perhaps this isn't the best way of doing it, but it appears to work fine after testing.

image

Fixes #14

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -178,6 +179,14 @@ module.exports = class RoleColorEverywhere extends Plugin {
     MessageContent.type.displayName = 'MessageContent';
   }
 
+  getRoleColor(channelId, memberId) {
+    const channel = this.channels.getChannel(channelId);
+    if (!channel) return "";
```
Comment (cyyynthia) [inline index.js]:
```suggestion
    if (!channel) {
      return null;
    }
```

File: index.js [hunk 2]
```diff
@@ -178,6 +179,14 @@ module.exports = class RoleColorEverywhere extends Plugin {
...
+    const member = this.members.getMember(channel.guild_id, memberId);
+    if (!member) return "";
```
Comment (cyyynthia) [inline index.js]:
```suggestion
    if (!member) {
      return null;
    }
```

File: index.js [hunk 3]
```diff
@@ -178,6 +179,14 @@ module.exports = class RoleColorEverywhere extends Plugin {
     MessageContent.type.displayName = 'MessageContent';
   }
 
+  getRoleColor(channelId, memberId) {
```
Comment (cyyynthia) [inline index.js]:
```suggestion
  getRoleColor (channelId, memberId) {
```

File: index.js [hunk 4]
```diff
@@ -158,8 +158,9 @@ module.exports = class RoleColorEverywhere extends Plugin {
     const MessageContent = await getModule(m => m.type?.displayName === 'MessageContent');
     inject('rce-messages', MessageContent, 'type', ([ props ], res) => {
       if (this.settings.get('messages', true)) {
+        const self = this;
```
Comment (cyyynthia) [inline index.js]: This is unnecessary

**Review by cyyynthia — CHANGES_REQUESTED** [review]

File: index.js (hunk 4 above)
Comment (Chew) [reply index.js]:
```suggestion
```

File: index.js [hunk 5]
```diff
@@ -159,7 +159,7 @@ module.exports = class RoleColorEverywhere extends Plugin {
     inject('rce-messages', MessageContent, 'type', ([ props ], res) => {
       if (this.settings.get('messages', true)) {
         res.props.style = {
-          color: props.message.colorString
+          color: self.getRoleColor(props.message.channel_id, props.message.author.id)
```
Comment (cyyynthia) [inline index.js]:
```suggestion
          color: this.getRoleColor(props.message.channel_id, props.message.author.id)
```

**Review by cyyynthia — CHANGES_REQUESTED** [review]

**Review by cyyynthia — APPROVED** [review]
